import type { Metadata } from "next";
import { AuthProvider } from "@/context/class-4/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps<"/">) {
  return (
    <AuthProvider>
      <div className="min-h-screen p-4 flex items-center justify-center">
        {children}
      </div>
    </AuthProvider>
  );
}
